names: 
  netG_name: "unet_256"
  netD_name: "basic_256_multi"
  where_add_type: "all"

init:
  _target_: models.BicycleGAN
  latent_dim: 8
  img_shape: [3, 128, 128]
  netG: ${model.names.netG_name}
  netD: ${model.names.netD_name}
  use_dropout: False
  init_type: "normal"
  ngf: 64
  ndf: 64
  init_gain: 0.02
  norm: "batch"
  nl: 'relu'
  upsample: 'bilinear'
  where_add: ${model.names.where_add_type}
  output_nc: 3